# Generated by Django 6.0.5 on 2026-05-08 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tactics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerTacticsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Data Name')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='Player Tactics JSON Data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Player Tactics Data',
                'verbose_name_plural': 'Player Tactics Data',
            },
        ),
    ]
