# Generated by Django 6.0.3 on 2026-05-03 18:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Player Name')),
                ('number', models.PositiveIntegerField(unique=True)),
                ('image', models.ImageField(blank=True, help_text='ارفع صورة اللاعب من هنا إذا أردت استبدال صورة JSON.', null=True, upload_to='players_images/', verbose_name='Player Image')),
                ('static_image', models.CharField(blank=True, default='', help_text='Image path from JSON, example: /static/images/raya.jpg', max_length=255)),
                ('position', models.CharField(choices=[('GK', 'Goalkeeper'), ('DEF', 'Defender'), ('MID', 'Midfielder'), ('FWD', 'Forward')], max_length=3)),
                ('secondary_position', models.CharField(blank=True, max_length=50)),
                ('birth_date', models.DateField()),
                ('height', models.PositiveIntegerField(help_text='Height in cm')),
                ('weight', models.PositiveIntegerField(help_text='Weight in kg')),
                ('preferred_foot', models.CharField(choices=[('Left', 'Left'), ('Right', 'Right'), ('Both', 'Both')], max_length=10)),
                ('market_value', models.DecimalField(decimal_places=2, help_text='Value in million Euro, example: 35.00', max_digits=12)),
                ('contract_start', models.DateField()),
                ('contract_expiry', models.DateField()),
                ('fitness_percentage', models.PositiveIntegerField(default=100, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('medical_status', models.CharField(choices=[('fit', 'Fit'), ('injured', 'Injured')], default='fit', max_length=20)),
                ('injury_meta', models.JSONField(blank=True, help_text='تفاصيل الإصابة بصيغة JSON لصفحة Medical Center', null=True)),
                ('goals', models.PositiveIntegerField(default=0)),
                ('assists', models.PositiveIntegerField(default=0)),
                ('matches_played', models.PositiveIntegerField(default=0)),
                ('minutes_played', models.PositiveIntegerField(default=0)),
                ('yellow_cards', models.PositiveIntegerField(default=0)),
                ('red_cards', models.PositiveIntegerField(default=0)),
                ('shots_on_target_pct', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('pass_accuracy', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('key_passes', models.PositiveIntegerField(default=0)),
                ('interceptions', models.PositiveIntegerField(default=0)),
                ('tackles_won', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('top_speed', models.FloatField(default=0.0, help_text='km/h')),
                ('distance_covered', models.FloatField(default=0.0, help_text='km per match average')),
                ('sprints', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='MatchPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('opponent', models.CharField(max_length=100)),
                ('competition', models.CharField(default='Premier League', max_length=100)),
                ('result', models.CharField(choices=[('W', 'Win'), ('D', 'Draw'), ('L', 'Loss')], max_length=10)),
                ('score', models.CharField(help_text='e.g. 2-1', max_length=10)),
                ('minutes_played', models.PositiveIntegerField()),
                ('goals', models.PositiveIntegerField(default=0)),
                ('assists', models.PositiveIntegerField(default=0)),
                ('card', models.CharField(choices=[('None', 'None'), ('Yellow', 'Yellow'), ('Red', 'Red')], default='None', max_length=20)),
                ('rating', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('distance_km', models.FloatField(default=0.0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_history', to='medical.player')),
            ],
            options={
                'verbose_name_plural': 'Match Performances',
                'ordering': ['-date'],
            },
        ),
    ]
