# Generated by Django 6.0.4 on 2026-05-03 21:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matchperformance',
            options={'ordering': ['-date'], 'verbose_name': 'Match Performance', 'verbose_name_plural': 'Match Performances'},
        ),
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['number'], 'verbose_name': 'Player', 'verbose_name_plural': 'Players'},
        ),
        migrations.AlterField(
            model_name='matchperformance',
            name='score',
            field=models.CharField(help_text='Example: 2-1', max_length=10),
        ),
        migrations.AlterField(
            model_name='player',
            name='birth_date',
            field=models.DateField(verbose_name='Birth Date'),
        ),
        migrations.AlterField(
            model_name='player',
            name='contract_expiry',
            field=models.DateField(verbose_name='Contract Expiry'),
        ),
        migrations.AlterField(
            model_name='player',
            name='contract_start',
            field=models.DateField(verbose_name='Contract Start'),
        ),
        migrations.AlterField(
            model_name='player',
            name='distance_covered',
            field=models.FloatField(default=0.0, help_text='Average distance covered per match in km'),
        ),
        migrations.AlterField(
            model_name='player',
            name='fitness_percentage',
            field=models.PositiveIntegerField(default=100, help_text='Fitness percentage from 0 to 100', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='player',
            name='image',
            field=models.ImageField(blank=True, help_text='ارفع صورة اللاعب من Django Admin إذا أردت استبدال صورة static.', null=True, upload_to='players_images/', verbose_name='Player Image'),
        ),
        migrations.AlterField(
            model_name='player',
            name='market_value',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Value in million Euro, example: 35.00', max_digits=12),
        ),
        migrations.AlterField(
            model_name='player',
            name='medical_status',
            field=models.CharField(choices=[('fit', 'Fit'), ('injured', 'Injured'), ('doubtful', 'Doubtful'), ('rehab', 'Rehab')], default='fit', max_length=20, verbose_name='Medical Status'),
        ),
        migrations.AlterField(
            model_name='player',
            name='number',
            field=models.PositiveIntegerField(unique=True, verbose_name='Shirt Number'),
        ),
        migrations.AlterField(
            model_name='player',
            name='pass_accuracy',
            field=models.FloatField(default=0.0, help_text='Pass accuracy percentage', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(choices=[('GK', 'Goalkeeper'), ('DEF', 'Defender'), ('MID', 'Midfielder'), ('FWD', 'Forward')], max_length=3, verbose_name='Main Position'),
        ),
        migrations.AlterField(
            model_name='player',
            name='preferred_foot',
            field=models.CharField(choices=[('Left', 'Left'), ('Right', 'Right'), ('Both', 'Both')], max_length=10, verbose_name='Preferred Foot'),
        ),
        migrations.AlterField(
            model_name='player',
            name='secondary_position',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Secondary Position'),
        ),
        migrations.AlterField(
            model_name='player',
            name='shots_on_target_pct',
            field=models.FloatField(default=0.0, help_text='Shots on target percentage', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='player',
            name='static_image',
            field=models.CharField(blank=True, default='', help_text='مسار الصورة القادمة من JSON مثل: /static/images/raya.jpg', max_length=255),
        ),
        migrations.AlterField(
            model_name='player',
            name='tackles_won',
            field=models.FloatField(default=0.0, help_text='Tackles won percentage', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='player',
            name='top_speed',
            field=models.FloatField(default=0.0, help_text='Top speed in km/h'),
        ),
    ]
