# Generated by Django 6.0.3 on 2026-05-03 18:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Player Name')),
                ('number', models.PositiveIntegerField(unique=True)),
                ('position', models.CharField(choices=[('GK', 'Goalkeeper'), ('DEF', 'Defender'), ('MID', 'Midfielder'), ('FWD', 'Forward')], max_length=3)),
                ('secondary_position', models.CharField(blank=True, default='—', max_length=50)),
                ('birth_date', models.DateField()),
                ('height', models.PositiveIntegerField(help_text='Height in cm')),
                ('weight', models.PositiveIntegerField(help_text='Weight in kg')),
                ('preferred_foot', models.CharField(choices=[('Left', 'Left'), ('Right', 'Right'), ('Both', 'Both')], max_length=10)),
                ('market_value', models.DecimalField(decimal_places=2, help_text='Market value in million Euro, e.g. 35.00 means €35m', max_digits=8)),
                ('trend', models.CharField(blank=True, default='€0', max_length=20)),
                ('trend_type', models.CharField(choices=[('up', 'Up'), ('down', 'Down'), ('neutral', 'Neutral')], default='neutral', max_length=10)),
                ('contract_start', models.DateField()),
                ('contract_expiry', models.DateField()),
                ('fitness_percentage', models.PositiveIntegerField(default=100, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('medical_status', models.CharField(choices=[('fit', 'Fit'), ('injured', 'Injured')], default='fit', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='players/')),
                ('image_url', models.CharField(blank=True, default='/static/images/white_gun.jpg', help_text='Static image path from JSON, e.g. /static/images/raya.jpg', max_length=255)),
                ('matches_played', models.PositiveIntegerField(default=0)),
                ('games_started', models.PositiveIntegerField(default=0)),
                ('minutes_played', models.PositiveIntegerField(default=0)),
                ('sub_in', models.PositiveIntegerField(default=0)),
                ('sub_out', models.PositiveIntegerField(default=0)),
                ('goals', models.PositiveIntegerField(default=0)),
                ('assists', models.PositiveIntegerField(default=0)),
                ('xg', models.FloatField(default=0.0, verbose_name='Expected Goals')),
                ('xa', models.FloatField(default=0.0, verbose_name='Expected Assists')),
                ('conversion_rate', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('shots', models.PositiveIntegerField(default=0)),
                ('shots_on_target_pct', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('shots_in_box', models.PositiveIntegerField(default=0)),
                ('shots_out_box', models.PositiveIntegerField(default=0)),
                ('free_kick_accuracy', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('yellow_cards', models.PositiveIntegerField(default=0)),
                ('red_cards', models.PositiveIntegerField(default=0)),
                ('fouls_committed', models.PositiveIntegerField(default=0)),
                ('fouls_suffered', models.PositiveIntegerField(default=0)),
                ('offsides', models.PositiveIntegerField(default=0)),
                ('pass_accuracy', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('key_passes', models.FloatField(default=0.0)),
                ('final_third_passes', models.PositiveIntegerField(default=0)),
                ('long_balls_accuracy', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('through_balls', models.PositiveIntegerField(default=0)),
                ('tackles_won', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('interceptions', models.FloatField(default=0.0)),
                ('ball_recoveries', models.FloatField(default=0.0)),
                ('blocked_shots', models.FloatField(default=0.0)),
                ('clearances', models.FloatField(default=0.0)),
                ('total_duels_won', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('aerial_duels_won', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('ground_duels_won', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('dribbles_success', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('distance_covered', models.FloatField(default=0.0, help_text='km per match average')),
                ('sprints', models.PositiveIntegerField(default=0)),
                ('top_speed', models.FloatField(default=0.0, help_text='km/h')),
                ('density', models.PositiveIntegerField(default=80, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='MatchPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('opponent', models.CharField(max_length=100)),
                ('competition', models.CharField(default='Premier League', max_length=100)),
                ('home', models.BooleanField(choices=[(True, 'Home'), (False, 'Away')], default=True)),
                ('result', models.CharField(choices=[('W', 'Win'), ('D', 'Draw'), ('L', 'Loss')], max_length=1)),
                ('score', models.CharField(help_text='e.g. 2-1', max_length=10)),
                ('minutes_played', models.PositiveIntegerField(default=0)),
                ('goals', models.PositiveIntegerField(default=0)),
                ('assists', models.PositiveIntegerField(default=0)),
                ('card', models.CharField(choices=[('None', 'None'), ('Yellow', 'Yellow'), ('Red', 'Red')], default='None', max_length=20)),
                ('rating', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('distance_km', models.FloatField(default=0.0)),
                ('saves', models.PositiveIntegerField(default=0)),
                ('punches', models.PositiveIntegerField(default=0)),
                ('tackles', models.PositiveIntegerField(default=0)),
                ('clearances', models.PositiveIntegerField(default=0)),
                ('chances_created', models.PositiveIntegerField(default=0)),
                ('interceptions', models.PositiveIntegerField(default=0)),
                ('shots', models.PositiveIntegerField(default=0)),
                ('dribbles', models.PositiveIntegerField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_history', to='performance.player')),
            ],
            options={
                'verbose_name': 'Match Performance',
                'verbose_name_plural': 'Match Performances',
                'ordering': ['-date'],
            },
        ),
    ]
