# Generated by Django 6.0.5 on 2026-05-08 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerPerformanceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Data Name')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='Performance JSON Data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Player Performance Data',
                'verbose_name_plural': 'Player Performance Data',
            },
        ),
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['number'], 'verbose_name': 'Player', 'verbose_name_plural': 'Players'},
        ),
    ]
