# Generated by Django 6.0.3 on 2026-05-03 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(default='Head Coach', max_length=100)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='coaches/')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('short', models.CharField(blank=True, max_length=50, null=True)),
                ('number', models.IntegerField()),
                ('position', models.CharField(blank=True, max_length=50, null=True)),
                ('primary', models.CharField(blank=True, max_length=50, null=True)),
                ('posGroup', models.CharField(blank=True, max_length=50, null=True)),
                ('nationality', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('height', models.IntegerField(blank=True, null=True)),
                ('weight', models.IntegerField(blank=True, null=True)),
                ('foot', models.CharField(blank=True, max_length=20, null=True)),
                ('valueN', models.FloatField(blank=True, null=True)),
                ('fitness', models.IntegerField(default=100)),
                ('img', models.ImageField(blank=True, null=True, upload_to='players/')),
                ('avatar_url', models.URLField(blank=True, max_length=500, null=True)),
                ('career_apps', models.IntegerField(default=0)),
                ('career_goals', models.IntegerField(default=0)),
                ('trophies', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='teams/')),
            ],
        ),
        migrations.CreateModel(
            name='PerformanceStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matches_played', models.IntegerField(default=0)),
                ('starts', models.IntegerField(default=0)),
                ('minutes', models.IntegerField(default=0)),
                ('goals', models.IntegerField(default=0)),
                ('assists', models.IntegerField(default=0)),
                ('expected_goals_xg', models.FloatField(default=0.0)),
                ('expected_assists_xa', models.FloatField(default=0.0)),
                ('conversion_rate', models.IntegerField(default=0, help_text='Percentage %')),
                ('total_shots', models.IntegerField(default=0)),
                ('shots_on_target_pct', models.IntegerField(default=0, help_text='Percentage %')),
                ('shots_in_box', models.IntegerField(default=0)),
                ('yellow_cards', models.IntegerField(default=0)),
                ('red_cards', models.IntegerField(default=0)),
                ('fouls_committed', models.IntegerField(default=0)),
                ('offsides', models.IntegerField(default=0)),
                ('pass_accuracy', models.IntegerField(default=0, help_text='Percentage %')),
                ('key_passes_per_90', models.FloatField(default=0.0)),
                ('final_third_passes', models.IntegerField(default=0)),
                ('long_ball_pct', models.IntegerField(default=0, help_text='Percentage %')),
                ('through_balls', models.IntegerField(default=0)),
                ('tackle_win_pct', models.IntegerField(default=0, help_text='Percentage %')),
                ('interceptions_per_90', models.FloatField(default=0.0)),
                ('ball_recoveries_per_90', models.FloatField(default=0.0)),
                ('total_duel_win_pct', models.IntegerField(default=0, help_text='Percentage %')),
                ('aerial_win_pct', models.IntegerField(default=0, help_text='Percentage %')),
                ('dribble_success_pct', models.IntegerField(default=0, help_text='Percentage %')),
                ('distance_covered', models.FloatField(default=0.0, help_text='Distance per 90 (km)')),
                ('high_intensity_sprints', models.IntegerField(default=0)),
                ('top_speed', models.FloatField(default=0.0, help_text='Top Speed (km/h)')),
                ('availability_pct', models.IntegerField(default=100, help_text='Percentage %')),
                ('motm_awards', models.IntegerField(default=0)),
                ('season_rating', models.FloatField(default=7.0)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='performance', to='compare.player')),
            ],
        ),
        migrations.CreateModel(
            name='InjuryHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('injury_type', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Fit', 'Fit'), ('Injured', 'Injured')], max_length=50)),
                ('days_out', models.IntegerField(default=0)),
                ('last_injury_date', models.DateField(blank=True, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='injuries', to='compare.player')),
            ],
        ),
        migrations.CreateModel(
            name='AIInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strengths', models.TextField(help_text='Separate by commas')),
                ('development_areas', models.TextField()),
                ('risk_level', models.CharField(choices=[('Very Low', 'Very Low'), ('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Low', max_length=20)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_insights', to='compare.player')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pace', models.IntegerField(default=0)),
                ('shooting', models.IntegerField(default=0)),
                ('passing', models.IntegerField(default=0)),
                ('dribbling', models.IntegerField(default=0)),
                ('defending', models.IntegerField(default=0)),
                ('physical', models.IntegerField(default=0)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='compare.player')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='players', to='compare.team'),
        ),
    ]
