# Generated by Django 6.0.3 on 2026-05-03 18:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='مثال: Home Dashboard أو Matches Data', max_length=100, unique=True)),
                ('data', models.JSONField(verbose_name='JSON Content')),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dashboard Data',
                'verbose_name_plural': 'Dashboard Data',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Player Name')),
                ('number', models.PositiveIntegerField(unique=True, verbose_name='Shirt Number')),
                ('image', models.ImageField(blank=True, default='players_images/white_gun.jpg', null=True, upload_to='players_images/', verbose_name='Player Image')),
                ('position', models.CharField(choices=[('GK', 'Goalkeeper'), ('DEF', 'Defender'), ('MID', 'Midfielder'), ('FWD', 'Forward')], default='MID', max_length=3)),
                ('secondary_position', models.CharField(blank=True, max_length=50)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, help_text='Height in cm', null=True)),
                ('weight', models.PositiveIntegerField(blank=True, help_text='Weight in kg', null=True)),
                ('preferred_foot', models.CharField(choices=[('Left', 'Left'), ('Right', 'Right'), ('Both', 'Both')], default='Right', max_length=10)),
                ('market_value', models.DecimalField(decimal_places=2, default=0.0, help_text='Value in Million Euro', max_digits=12)),
                ('contract_start', models.DateField(blank=True, null=True)),
                ('contract_expiry', models.DateField(blank=True, null=True)),
                ('fitness_percentage', models.PositiveIntegerField(default=100, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Fitness %')),
                ('medical_status', models.CharField(choices=[('fit', 'Fit'), ('injured', 'Injured')], default='fit', max_length=20)),
                ('injury_meta', models.JSONField(blank=True, help_text="JSON data: { 'type': '...', 'recovery': '...', 'history': [...] }", null=True)),
                ('goals', models.PositiveIntegerField(default=0)),
                ('assists', models.PositiveIntegerField(default=0)),
                ('matches_played', models.PositiveIntegerField(default=0)),
                ('minutes_played', models.PositiveIntegerField(default=0)),
                ('yellow_cards', models.PositiveIntegerField(default=0)),
                ('red_cards', models.PositiveIntegerField(default=0)),
                ('shots_on_target_pct', models.FloatField(default=0.0, verbose_name='Shots on Target %')),
                ('pass_accuracy', models.FloatField(default=0.0, verbose_name='Pass Accuracy %')),
                ('key_passes', models.PositiveIntegerField(default=0)),
                ('interceptions', models.PositiveIntegerField(default=0)),
                ('tackles_won', models.PositiveIntegerField(default=0)),
                ('top_speed', models.FloatField(default=0.0, help_text='km/h')),
                ('distance_covered', models.FloatField(default=0.0, help_text='Avg km per match')),
                ('sprints', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Player',
                'verbose_name_plural': 'Players',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='MatchPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('opponent', models.CharField(max_length=100)),
                ('competition', models.CharField(default='Premier League', max_length=100)),
                ('result', models.CharField(choices=[('W', 'Win'), ('D', 'Draw'), ('L', 'Loss')], max_length=10)),
                ('score', models.CharField(help_text='e.g. 2-1', max_length=10)),
                ('minutes_played', models.PositiveIntegerField(default=0)),
                ('goals', models.PositiveIntegerField(default=0)),
                ('assists', models.PositiveIntegerField(default=0)),
                ('card', models.CharField(choices=[('None', 'None'), ('Yellow', 'Yellow'), ('Red', 'Red')], default='None', max_length=20)),
                ('rating', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('distance_km', models.FloatField(default=0.0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_history', to='index.player')),
            ],
            options={
                'verbose_name': 'Match Performance',
                'verbose_name_plural': 'Match Performances',
                'ordering': ['-date'],
            },
        ),
    ]
