# Generated by Django 6.0.5 on 2026-05-08 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calender', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarTypeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_key', models.CharField(help_text='Type key from JSON file مثل match أو training', max_length=30, unique=True)),
                ('label', models.CharField(max_length=100)),
                ('icon', models.CharField(max_length=100)),
                ('badge', models.CharField(max_length=100)),
                ('short', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Calendar Type Config',
                'verbose_name_plural': 'Calendar Type Configs',
            },
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='event_id',
            field=models.CharField(blank=True, help_text='Unique ID from JSON file, مثل s01 أو m01', max_length=50, null=True, unique=True),
        ),
    ]
