# Generated by Django 6.0.5 on 2026-05-08 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calender', '0002_calendartypeconfig_calendarevent_event_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calendartypeconfig',
            options={'ordering': ['type_key'], 'verbose_name': 'Calendar Type Config', 'verbose_name_plural': 'Calendar Type Configs'},
        ),
        migrations.RemoveField(
            model_name='calendarevent',
            name='created_at',
        ),
    ]
