# Generated by Django 6.0.3 on 2026-05-03 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('short', models.CharField(blank=True, help_text='الاسم المختصر المستخدم في التشكيلة', max_length=50, null=True)),
                ('number', models.IntegerField()),
                ('primary', models.CharField(blank=True, help_text='المركز الأساسي: GK, CB, RW...', max_length=50, null=True)),
                ('posGroup', models.CharField(blank=True, help_text='مجموعة المركز: GK, DEF, MID, FWD', max_length=50, null=True)),
                ('nationality', models.CharField(blank=True, max_length=50, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('weight', models.IntegerField(blank=True, null=True)),
                ('foot', models.CharField(choices=[('Right', 'Right'), ('Left', 'Left'), ('Both', 'Both')], default='Right', max_length=20)),
                ('fitness', models.IntegerField(default=100)),
                ('img', models.CharField(blank=True, help_text='رابط الصورة الثابتة أو المسار', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='teams/')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_id', models.CharField(help_text='مثال: dribbling', max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(help_text='اسم أيقونة جوجل', max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PerformanceStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matches_played', models.IntegerField(default=0)),
                ('starts', models.IntegerField(default=0)),
                ('minutes', models.IntegerField(default=0)),
                ('goals', models.IntegerField(default=0)),
                ('assists', models.IntegerField(default=0)),
                ('expected_goals_xg', models.FloatField(default=0.0)),
                ('expected_assists_xa', models.FloatField(default=0.0)),
                ('pass_accuracy', models.IntegerField(default=0)),
                ('tackles_win_pct', models.IntegerField(default=0)),
                ('top_speed', models.FloatField(default=0.0)),
                ('distance_per_90', models.FloatField(default=0.0)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='performance', to='training.player')),
            ],
        ),
        migrations.CreateModel(
            name='InjuryHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Fit', 'Fit'), ('Injured', 'Injured')], default='Fit', max_length=50)),
                ('injury_type', models.CharField(blank=True, max_length=100, null=True)),
                ('days_out', models.IntegerField(default=0)),
                ('last_injury_date', models.DateField(blank=True, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='injuries', to='training.player')),
            ],
        ),
        migrations.CreateModel(
            name='AIInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strengths', models.TextField(help_text='نقاط القوة')),
                ('development_areas', models.TextField(help_text='نقاط التطوير')),
                ('risk_level', models.CharField(default='Low', help_text='مستوى خطر الإصابة', max_length=50)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_insights', to='training.player')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pace', models.IntegerField(default=50)),
                ('shooting', models.IntegerField(default=50)),
                ('passing', models.IntegerField(default=50)),
                ('dribbling', models.IntegerField(default=50)),
                ('defending', models.IntegerField(default=50)),
                ('physical', models.IntegerField(default=50)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='training.player')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='players', to='training.team'),
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(default='Head Coach', max_length=100)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='coaches/')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='training.team')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingDrill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drill_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('short_name', models.CharField(max_length=100)),
                ('focus_label', models.CharField(max_length=100)),
                ('intensity', models.CharField(max_length=50)),
                ('duration', models.IntegerField(help_text='المدة بالدقائق')),
                ('attrs', models.CharField(help_text='مفصولة بفاصلة، مثال: PAS, VIS', max_length=200)),
                ('video', models.URLField(blank=True, max_length=500, null=True)),
                ('description', models.TextField()),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drills', to='training.trainingsection')),
            ],
        ),
    ]
