# Generated by Django 5.0.14 on 2026-05-14 22:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_publishedtrainingsession_alter_aiinsight_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='user',
            field=models.OneToOneField(blank=True, help_text='ربط اللاعب بحساب المستخدم في Django Admin', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='aiinsight',
            name='development_areas',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='aiinsight',
            name='risk_level',
            field=models.CharField(default='Low', max_length=50),
        ),
        migrations.AlterField(
            model_name='aiinsight',
            name='strengths',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='player',
            name='img',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='posGroup',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='primary',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='short',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='playertrainingdata',
            name='data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='playertrainingdata',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='publishedtrainingsession',
            name='session_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='trainingdrill',
            name='attrs',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='trainingdrill',
            name='duration',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='trainingdrill',
            name='intensity',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='trainingsection',
            name='icon',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='trainingsection',
            name='section_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
