# Generated by Django 6.0.5 on 2026-05-20 13:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0005_alter_aiinsight_id_alter_coach_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playertrainingdata',
            options={},
        ),
        migrations.AlterModelOptions(
            name='publishedtrainingsession',
            options={},
        ),
        migrations.AlterModelOptions(
            name='trainingdrill',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='trainingsection',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='aiinsight',
            name='risk_level',
        ),
        migrations.RemoveField(
            model_name='aiinsight',
            name='strengths',
        ),
        migrations.RemoveField(
            model_name='coach',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='injuryhistory',
            name='days_out',
        ),
        migrations.RemoveField(
            model_name='injuryhistory',
            name='injury_type',
        ),
        migrations.RemoveField(
            model_name='performancestat',
            name='distance_per_90',
        ),
        migrations.RemoveField(
            model_name='performancestat',
            name='expected_assists_xa',
        ),
        migrations.RemoveField(
            model_name='performancestat',
            name='expected_goals_xg',
        ),
        migrations.RemoveField(
            model_name='performancestat',
            name='matches_played',
        ),
        migrations.RemoveField(
            model_name='performancestat',
            name='pass_accuracy',
        ),
        migrations.RemoveField(
            model_name='performancestat',
            name='starts',
        ),
        migrations.RemoveField(
            model_name='performancestat',
            name='tackles_win_pct',
        ),
        migrations.RemoveField(
            model_name='performancestat',
            name='top_speed',
        ),
        migrations.RemoveField(
            model_name='player',
            name='age',
        ),
        migrations.RemoveField(
            model_name='player',
            name='foot',
        ),
        migrations.RemoveField(
            model_name='player',
            name='height',
        ),
        migrations.RemoveField(
            model_name='player',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='player',
            name='weight',
        ),
        migrations.RemoveField(
            model_name='playerattribute',
            name='defending',
        ),
        migrations.RemoveField(
            model_name='playerattribute',
            name='dribbling',
        ),
        migrations.RemoveField(
            model_name='playerattribute',
            name='pace',
        ),
        migrations.RemoveField(
            model_name='playerattribute',
            name='passing',
        ),
        migrations.RemoveField(
            model_name='playerattribute',
            name='physical',
        ),
        migrations.RemoveField(
            model_name='playerattribute',
            name='shooting',
        ),
        migrations.RemoveField(
            model_name='playertrainingdata',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='playertrainingdata',
            name='name',
        ),
        migrations.RemoveField(
            model_name='playertrainingdata',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='aiinsight',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coach',
            name='img',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='playerattribute',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='playerattribute',
            name='value',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='aiinsight',
            name='development_areas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aiinsight',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_insights', to='training.player'),
        ),
        migrations.AlterField(
            model_name='coach',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='coach',
            name='role',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='coach',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coaches', to='training.team'),
        ),
        migrations.AlterField(
            model_name='injuryhistory',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='injuries', to='training.player'),
        ),
        migrations.AlterField(
            model_name='injuryhistory',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='performancestat',
            name='player',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='performance', to='training.player'),
        ),
        migrations.AlterField(
            model_name='player',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='posGroup',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='primary',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='training.team'),
        ),
        migrations.AlterField(
            model_name='player',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='playerattribute',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='training.player'),
        ),
        migrations.AlterField(
            model_name='publishedtrainingsession',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='logo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='trainingdrill',
            name='attrs',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainingdrill',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainingdrill',
            name='duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='trainingdrill',
            name='focus_label',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trainingdrill',
            name='intensity',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='trainingdrill',
            name='short_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trainingdrill',
            name='video',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainingsection',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainingsection',
            name='icon',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterModelTable(
            name='aiinsight',
            table='training_aiinsight',
        ),
        migrations.AlterModelTable(
            name='coach',
            table='training_coach',
        ),
        migrations.AlterModelTable(
            name='injuryhistory',
            table='training_injuryhistory',
        ),
        migrations.AlterModelTable(
            name='performancestat',
            table='training_performancestat',
        ),
        migrations.AlterModelTable(
            name='player',
            table='training_player',
        ),
        migrations.AlterModelTable(
            name='playerattribute',
            table='training_playerattribute',
        ),
        migrations.AlterModelTable(
            name='playertrainingdata',
            table='training_playertrainingdata',
        ),
        migrations.AlterModelTable(
            name='publishedtrainingsession',
            table='training_publishedtrainingsession',
        ),
        migrations.AlterModelTable(
            name='team',
            table='training_team',
        ),
        migrations.AlterModelTable(
            name='trainingdrill',
            table='training_trainingdrill',
        ),
        migrations.AlterModelTable(
            name='trainingsection',
            table='training_trainingsection',
        ),
    ]
